apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: english-greeter-monitor
  labels:
    release: prometheus
spec:
  jobLabel: english-app
  selector:
    matchLabels:
      app: "english-greeter"
  namespaceSelector:
    matchNames: 
    - default
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 10s