# apiVersion: v1 # version of kubernetes you are writing
# kind: Service # we are creating a service object
# metadata:
#   name: english-service # the name of the service in kubernetes. does not have any real impact on code
# spec: # technial specifications of the service
#   type: ClusterIP # Type of service are the other types LoadBalancer, ClusterIP
#   selector: # Selectors specify what pods does this service expose
#     app: english-app # This selects the pod we created, defined by either the pod or the deployment manifest
#   ports: 
#     - name: http
#     - protocol: TCP
#       port: 80 # 80 is the standard http port 
#       targetPort: 8080 # what port on the pod does this service listen to

apiVersion: "v1"
kind: "Service"
metadata:
  name: "english-greeter-service"
  namespace: "default"
  labels:
    app: "english-greeter"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "english-greeter"
  type: "ClusterIP"