
controller:
  adminPassword: "password"
  jenkinsUriPrefix: "/jenkins"
  ingress:
    enabled: true
    # Override for the default paths that map requests to the backend
    paths: []
    apiVersion: networking.k8s.io/v1
    ingressClassName: nginx
    path: "/jenkins"
    hostName:
    tls:
