controller:
  installPlugins:
  - kubernetes:3600.v144b_cd192ca_a_
  - workflow-aggregator:581.v0c46fa_697ffd
  - git:4.11.3
  - configuration-as-code:1429.v09b_044a_c93de
  - docker-workflow:1.29
  - workflow-aggregator:590.v6a_d052e5a_a_b_5
  - github-branch-source:1677.v731f745ea_0cf
  - docker-plugin:1.2.9
  - pipeline-stage-view:2.24
  - timestamper:1.18
  - github:1.36.0
  JCasC:
    defaultConfig: true
  adminPassword: "password"
  jenkinsUriPrefix: "/jenkins"
  ingress:
    enabled: true
    # Override for the default paths that map requests to the backend
    paths: []
    apiVersion: networking.k8s.io/v1
    ingressClassName: nginx
    path: "/jenkins"
agent:
  podTemplates:
    greeting: |
        - name: greeting
          label: jenkins-greeting
          serviceAccount: jenkins
          containers:
          - name: docker
            image: docker:20-dind
            privileged: true